- task: Maven@4
  displayName: 'Run Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-X'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.7'
    mavenVersionOption: 'Default'